---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: {{ .Name }}
  log_level: error
  state_top:
    base:
      '*':
        - {{ .Name }}

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: ubuntu-14.04
    provisioner:
      salt_install: apt
  - name: ubuntu-16.04
    provisioner:
      salt_install: apt

suites:
  - name: default
